apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "dag-example-spark-{{ macros.datetime.now().strftime("%Y-%m-%d-%H-%M-%S") }}-{{ task_instance.try_number }}"
  namespace: airflow
spec:
  timeToLiveSeconds: 30
  sparkConf:
    # spark.jars.packages: "org.apache.hadoop:hadoop-aws:3.2.0,org.apache.spark:spark-avro_2.12:3.0.1"
    spark.jars.packages: "software.amazon.awssdk:bundle:2.17.288,software.amazon.awssdk:url-connection-client:2.17.288,com.amazonaws:aws-java-sdk-bundle:1.12.319,org.apache.hadoop:hadoop-aws:3.2.0"
    spark.jars.ivy: /tmp/.ivy
    spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
    spark.kubernetes.local.dirs.tmpfs: "true"
    spark.kubernetes.file.upload.path: "/opt/spark/work-dir"
    spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
  hadoopConf:
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "kleinkauff/spark-py"
  mainClass: org.apache.spark.examples.SparkPi
  imagePullPolicy: IfNotPresent
  mainApplicationFile: s3a://spark-jobs-jho/pi.py #local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "4g"
    labels:
      version: 3.1.1
    serviceAccount: spark-operator
  executor:
    cores: 1
    instances: 1
    memory: "475M"
    labels:
      version: 3.1.1
    serviceAccount: spark-operator